<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_December</name>
   <tag></tag>
   <elementGuidId>392f729d-915c-43ca-b400-2283d34da4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/form/div[12]/div[2]/div/div/div[2]/div[2]/div[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.visible.menu.transition > div.active.selected.item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f1ea2412-cc93-4eeb-8638-fda86edb2d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e000d521-3bbe-4112-bfcd-6c8eebc867a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21ae3b4e-fd03-4fc8-b40f-d2e50e337f8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8055f2a6-3515-4a8d-8bf3-3b4c6596d8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active selected item</value>
      <webElementGuid>e951294b-029f-492c-ac36-7c6e1de1af3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>December</value>
      <webElementGuid>77de99ae-ddbc-4a05-8fc2-31cc6bee1220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/form[@class=&quot;ui form segment custom-form-container&quot;]/div[@class=&quot;two fields&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui field&quot;]/div[@class=&quot;three fields custom-address-container&quot;]/div[@class=&quot;ui active visible selection upward dropdown&quot;]/div[@class=&quot;visible menu transition&quot;]/div[@class=&quot;active selected item&quot;]</value>
      <webElementGuid>ca01beb1-5a55-45ef-ae03-348837eef898</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/form/div[12]/div[2]/div/div/div[2]/div[2]/div[13]</value>
      <webElementGuid>c1de22c7-f35e-464c-9b36-83b6a2a5c769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='November'])[1]/following::div[1]</value>
      <webElementGuid>86ab955a-666e-44a6-88c3-b80c0fdc5ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='October'])[1]/following::div[2]</value>
      <webElementGuid>ddcddc96-869e-49ee-9694-28fec41b1428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifier'])[1]/preceding::div[2]</value>
      <webElementGuid>aef1a85d-5608-4c7c-99dd-feb3ff15691b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[13]</value>
      <webElementGuid>621f58cb-6086-49b7-898c-bd7fb8f7b16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'December' or . = 'December')]</value>
      <webElementGuid>a2769d37-0a64-44b1-8439-34929543ab30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
