<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Public</name>
   <tag></tag>
   <elementGuidId>794b7d96-d0c2-4172-a221-31e868ebfafa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div[2]/form/div[3]/div/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui.small.fluid.positive.toggle.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f68b1c20-c633-48c2-a9e8-1f149e045b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui small fluid positive toggle button</value>
      <webElementGuid>6d6adae2-a806-4fc0-b7fa-b2f0a2ccd68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>551d8788-073f-4be0-abc0-64e522b57cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Public</value>
      <webElementGuid>1151e288-b164-4ebc-9430-cc86dec55a4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/form[@class=&quot;ui form segment custom-form-container&quot;]/div[@class=&quot;two fields&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui field&quot;]/div[@class=&quot;fields&quot;]/div[@class=&quot;four wide field&quot;]/button[@class=&quot;ui small fluid positive toggle button&quot;]</value>
      <webElementGuid>ca030113-4bbb-41eb-973f-6ee4e11d2d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/form/div[3]/div/div/div/div/button</value>
      <webElementGuid>0df7ebd3-eebd-445d-869b-6ad106793154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access'])[1]/following::button[1]</value>
      <webElementGuid>dcb9db10-f4fa-43fa-8dcc-5b2d8a605def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simform'])[3]/following::button[1]</value>
      <webElementGuid>e1902ed1-db2a-46fe-a6df-a0662fa5aab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select users allowed access.'])[1]/preceding::button[1]</value>
      <webElementGuid>b764906c-020f-4250-aa2e-786945cd311a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deep Patel'])[2]/preceding::button[1]</value>
      <webElementGuid>364d6d27-9541-4ad0-8aa1-bffc4848829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Public']/parent::*</value>
      <webElementGuid>2d722fc1-fb13-4250-9f4f-9b2674807e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>066f30f5-8639-4da9-9f68-2d5501f6cecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Public' or . = 'Public')]</value>
      <webElementGuid>324aa00f-9d3a-42d8-8126-5e9cc174758d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
