<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Private</name>
   <tag></tag>
   <elementGuidId>41bfd623-9a4c-485a-a8aa-7edd53a52977</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui.small.fluid.negative.toggle.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>258574c6-13ca-4993-9168-4145d7c7f532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui small fluid negative toggle button</value>
      <webElementGuid>244f0e91-044a-4e51-913a-ac47502794d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-pressed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>acbc627c-3878-4332-a393-56f1462e5bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Private</value>
      <webElementGuid>27afa159-1c23-4924-906f-4c9ab9335711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;ui fluid container&quot;]/div[@class=&quot;ui fluid container main-content&quot;]/form[@class=&quot;ui form segment custom-form-container&quot;]/div[@class=&quot;two fields&quot;]/div[@class=&quot;field&quot;]/div[@class=&quot;ui field&quot;]/div[@class=&quot;fields&quot;]/div[@class=&quot;four wide field&quot;]/button[@class=&quot;ui small fluid negative toggle button&quot;]</value>
      <webElementGuid>f71c6709-505d-466b-a971-ba1df286c42b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div[2]/form/div[3]/div/div/div/div/button</value>
      <webElementGuid>93aff778-c28e-4de0-b710-56e75a737be1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Access'])[1]/following::button[1]</value>
      <webElementGuid>19fc624f-688e-45c8-b420-424b90070872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simform'])[3]/following::button[1]</value>
      <webElementGuid>7440aa37-0d1b-412d-85c4-47c81c132e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select users allowed access.'])[1]/preceding::button[1]</value>
      <webElementGuid>e3965436-9e52-4970-9554-ec8497b3292e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deep Patel'])[2]/preceding::button[1]</value>
      <webElementGuid>c026eb4c-1c99-45f4-9989-e98f2b27b61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Private']/parent::*</value>
      <webElementGuid>fcb4bc3d-56e3-4915-bcc3-65b0786b913e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/button</value>
      <webElementGuid>a0639744-55a9-4020-9c1e-6e4c36b5b66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Private' or . = 'Private')]</value>
      <webElementGuid>3576dc46-80be-4ce0-a669-ce3bcd00218b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
