<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>createContactusingCSV</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>da367611-0432-4cb2-9ffd-c38b4d375e96</testSuiteGuid>
   <testCaseLink>
      <guid>b754eef1-3336-4b75-bb3c-a4b4462c4026</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Day-04/createContactUsingCSV</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c8e0e3af-05f5-4d52-b207-4556ca80e394</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/testdata</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c8e0e3af-05f5-4d52-b207-4556ca80e394</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FirstName</value>
         <variableId>b852e5ef-ada6-4c76-89e3-c3e0d2903be8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c8e0e3af-05f5-4d52-b207-4556ca80e394</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>LastName</value>
         <variableId>bccd17fa-934e-4030-893c-e8c15d7e77cc</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
